# public/admin/config.yml - CONFIGURACIÓN CORREGIDA
backend:
  name: git-gateway
  branch: main

# Configuración de medios
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Configuración del sitio
site_url: https://canicat.netlify.app
display_url: https://canicat.netlify.app
logo_url: /images/logo.png

# Configuración del editor
editor:
  preview: true

# Configuración de búsqueda
search: true

collections:
  # 👤 AUTORES
  - name: "autores"
    label: "👤 Autores"
    folder: "src/content/autores"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    summary: "{{name}} - {{role}}"
    sortable_fields: ['name', 'role', 'status']
    fields:
      - { label: "Nombre completo", name: "name", widget: "string", required: true }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Solo minúsculas, números y guiones"], required: true }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Biografía completa", name: "bio", widget: "text", required: true }
      - { label: "Biografía corta", name: "shortBio", widget: "text", required: false }
      - { label: "Rol/Título", name: "role", widget: "string", required: false, default: "Editor" }
      - { label: "Especialidades", name: "specialties", widget: "list", required: false }
      - { label: "Años de experiencia", name: "experience", widget: "string", required: false }
      - { label: "Credenciales", name: "credentials", widget: "list", required: false }
      - { label: "Sitio web", name: "website", widget: "string", required: false }
      - label: "Redes sociales"
        name: "socialMedia"
        widget: "object"
        required: false
        fields:
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "Facebook", name: "facebook", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
          - { label: "YouTube", name: "youtube", widget: "string", required: false }
      - { label: "Estado", name: "status", widget: "select", options: ["active", "inactive"], default: "active" }
      - { label: "Autor destacado", name: "featured", widget: "boolean", default: false }
      - { label: "Número de artículos", name: "articlesCount", widget: "number", default: 0 }
      - { label: "SEO Título", name: "seoTitle", widget: "string", required: false }
      - { label: "SEO Descripción", name: "seoDescription", widget: "text", required: false }
      - { label: "Contenido adicional", name: "body", widget: "markdown", required: false }

  # 📂 CATEGORÍAS
  - name: "categorias"
    label: "📂 Categorías"
    folder: "src/content/categorias"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    summary: "{{name}} ({{order}})"
    sortable_fields: ['name', 'order', 'featured']
    fields:
      - { label: "Nombre", name: "name", widget: "string", required: true }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Solo minúsculas, números y guiones"], required: true }
      - { label: "Descripción", name: "description", widget: "text", required: true }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Ícono (emoji)", name: "icon", widget: "string", required: false, default: "📁" }
      - label: "Color"
        name: "color"
        widget: "select"
        default: "primary"
        options:
          - { label: "Azul (Primario)", value: "primary" }
          - { label: "Coral (Secundario)", value: "secondary" }
          - { label: "Verde (Éxito)", value: "success" }
          - { label: "Azul claro (Info)", value: "info" }
          - { label: "Amarillo (Advertencia)", value: "warning" }
          - { label: "Rojo (Peligro)", value: "danger" }
      - { label: "Categoría padre", name: "parentCategory", widget: "relation", collection: "categorias", search_fields: ["name"], value_field: "slug", display_fields: ["name"], required: false }
      - { label: "Subcategorías", name: "subcategories", widget: "list", required: false }
      - { label: "Orden", name: "order", widget: "number", min: 0, default: 0 }
      - { label: "Mostrar en navegación", name: "showInNavigation", widget: "boolean", default: true }
      - { label: "Mostrar en sidebar", name: "showInSidebar", widget: "boolean", default: true }
      - { label: "Categoría destacada", name: "featured", widget: "boolean", default: false }
      - { label: "Número de artículos", name: "articleCount", widget: "number", default: 0 }
      - { label: "SEO Título", name: "seoTitle", widget: "string", required: false }
      - { label: "SEO Descripción", name: "seoDescription", widget: "text", required: false }
      - { label: "Contenido", name: "body", widget: "markdown", required: false }

  # 🏷️ ETIQUETAS
  - name: "etiquetas"
    label: "🏷️ Etiquetas"
    folder: "src/content/etiquetas"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    summary: "{{name}}"
    fields:
      - { label: "Nombre", name: "name", widget: "string", required: true }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Solo minúsculas, números y guiones"], required: true }
      - { label: "Descripción", name: "description", widget: "text", required: false }
      - { label: "Color", name: "color", widget: "color", required: false }
      - { label: "Categorías relacionadas", name: "categories", widget: "relation", collection: "categorias", search_fields: ["name"], value_field: "slug", display_fields: ["name"], multiple: true, required: false }
      - { label: "Etiqueta destacada", name: "featured", widget: "boolean", default: false }
      - { label: "Contador de uso", name: "count", widget: "number", default: 0 }
      - { label: "Contenido", name: "body", widget: "markdown", required: false }

  # 📰 ARTÍCULOS
  - name: "articulos"
    label: "📰 Artículos"
    folder: "src/content/articulos"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{author}} ({{date}})"
    sortable_fields: ['title', 'date', 'author', 'category', 'status', 'featured']
    view_filters:
      - label: "Borradores"
        field: status
        pattern: "draft"
      - label: "Publicados"
        field: status
        pattern: "published"
      - label: "Destacados"
        field: featured
        pattern: true
    fields:
      # Información básica
      - { label: "Título", name: "title", widget: "string", required: true }
      - { label: "Descripción/Bajada", name: "description", widget: "text", required: true }
      - { label: "Extracto", name: "excerpt", widget: "text", required: false }
      
      # Fechas
      - { label: "Fecha de publicación", name: "date", widget: "datetime", required: true }
      - { label: "Fecha de actualización", name: "updatedAt", widget: "datetime", required: false }
      - { label: "Fecha de publicación programada", name: "publishedAt", widget: "datetime", required: false }
      
      # Autor
      - { label: "Autor", name: "author", widget: "relation", collection: "autores", search_fields: ["name"], value_field: "slug", display_fields: ["name", "role"], required: true }
      - { label: "Biografía personalizada del autor", name: "authorBio", widget: "text", required: false }
      - { label: "Colaboradores", name: "contributors", widget: "relation", collection: "autores", search_fields: ["name"], value_field: "slug", display_fields: ["name"], multiple: true, required: false }
      
      # Clasificación
      - { label: "Categoría", name: "category", widget: "relation", collection: "categorias", search_fields: ["name"], value_field: "slug", display_fields: ["name"], required: true }
      - { label: "Etiquetas", name: "tags", widget: "relation", collection: "etiquetas", search_fields: ["name"], value_field: "slug", display_fields: ["name"], multiple: true, required: false }
      
      # Media
      - { label: "Imagen principal", name: "image", widget: "image", required: true }
      - { label: "Texto alternativo de imagen", name: "imageAlt", widget: "string", required: false }
      - label: "Galería de imágenes"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - { label: "Imagen", name: "url", widget: "image" }
          - { label: "Texto alternativo", name: "alt", widget: "string" }
          - { label: "Leyenda", name: "caption", widget: "string", required: false }
      
      # Metadatos
      - { label: "Tiempo de lectura (minutos)", name: "readingTime", widget: "number", min: 1, default: 5 }
      - { label: "Dificultad", name: "difficulty", widget: "select", options: ["beginner", "intermediate", "advanced"], required: false }
      - { label: "Contador de palabras", name: "wordCount", widget: "number", required: false }
      
      # Estado
      - { label: "Estado", name: "status", widget: "select", options: ["draft", "published", "archived"], default: "draft" }
      - { label: "Artículo destacado", name: "featured", widget: "boolean", default: false }
      - { label: "Trending", name: "trending", widget: "boolean", default: false }
      - { label: "Contenido premium", name: "premium", widget: "boolean", default: false }
      
      # Engagement (campos informativos)
      - { label: "Visualizaciones", name: "views", widget: "number", default: 0, required: false }
      - { label: "Me gusta", name: "likes", widget: "number", default: 0, required: false }
      - { label: "Compartidos", name: "shares", widget: "number", default: 0, required: false }
      
      # Artículos relacionados
      - { label: "Artículos relacionados", name: "relatedArticles", widget: "relation", collection: "articulos", search_fields: ["title"], value_field: "slug", display_fields: ["title"], multiple: true, required: false }
      
      # SEO
      - { label: "SEO Título", name: "seoTitle", widget: "string", required: false }
      - { label: "SEO Descripción", name: "seoDescription", widget: "text", required: false }
      - { label: "URL canónica", name: "canonicalUrl", widget: "string", required: false }
      - { label: "No indexar", name: "noindex", widget: "boolean", default: false }
      - { label: "Tipo de artículo", name: "articleType", widget: "select", options: ["Article", "NewsArticle", "BlogPosting"], default: "Article" }
      - { label: "Palabras clave", name: "keywords", widget: "list", required: false }
      
      # Contenido - CONFIGURACIÓN MEJORADA PARA CURSIVAS
      - label: "Contenido"
        name: "body"
        widget: "markdown"
        hint: "⚠️ EVITA usar cursivas (*texto*) temporalmente por problemas de renderizado. Usa **negritas** y texto normal. Modo Raw recomendado."
        modes: ["rich_text", "raw"]
        show_raw: true

  # 📄 PÁGINAS
  - name: "paginas"
    label: "📄 Páginas"
    folder: "src/content/paginas"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} ({{status}})"
    sortable_fields: ['title', 'status', 'createdAt']
    fields:
      - { label: "Título", name: "title", widget: "string", required: true }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Solo minúsculas, números y guiones"], required: true }
      - { label: "Descripción", name: "description", widget: "text", required: false }
      
      # Fechas
      - { label: "Fecha de creación", name: "createdAt", widget: "datetime", required: true }
      - { label: "Fecha de actualización", name: "updatedAt", widget: "datetime", required: true }
      
      # Configuración
      - { label: "Layout", name: "layout", widget: "select", options: ["default", "full-width", "sidebar", "landing"], default: "default" }
      - { label: "Template personalizado", name: "template", widget: "string", required: false }
      
      # Navegación
      - { label: "Mostrar en navegación", name: "showInNavigation", widget: "boolean", default: false }
      - { label: "Mostrar en footer", name: "showInFooter", widget: "boolean", default: true }
      - { label: "Orden en navegación", name: "navigationOrder", widget: "number", required: false }
      
      # Estado
      - { label: "Estado", name: "status", widget: "select", options: ["draft", "published", "archived"], default: "draft" }
      
      # SEO
      - { label: "SEO Título", name: "seoTitle", widget: "string", required: false }
      - { label: "SEO Descripción", name: "seoDescription", widget: "text", required: false }
      - { label: "Imagen SEO", name: "image", widget: "image", required: false }
      - { label: "No indexar", name: "noindex", widget: "boolean", default: false }
      
      # Contenido
      - { label: "Contenido", name: "body", widget: "markdown", required: true }