# public/admin/config.yml - VERSIÓN CORREGIDA FINAL
backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  # Colección de autores (DEBE IR PRIMERO)
  - name: "authors"
    label: "Autores"
    folder: "src/content/autores"
    create: true
    slug: "{{fields.slug}}"  # ✅ CAMBIO CRÍTICO
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Slug debe ser minúsculas, números y guiones"] }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Biografía", name: "bio", widget: "text" }
      - { label: "Biografía corta", name: "shortBio", widget: "text", required: false }
      - { label: "Rol", name: "role", widget: "string", required: false }
      - { label: "Especialidades", name: "specialties", widget: "list", required: false }
      - { label: "Sitio web", name: "website", widget: "string", required: false }
      - label: "Redes sociales"
        name: "socialMedia"
        widget: "object"
        required: false
        fields:
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "Facebook", name: "facebook", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
      - { label: "Estado", name: "status", widget: "select", options: ["active", "inactive"], default: "active" }
      - { label: "SEO Título", name: "seoTitle", widget: "string", required: false }
      - { label: "SEO Descripción", name: "seoDescription", widget: "string", required: false }

  # Colección de categorías (SEGUNDO)
  - name: "categories"
    label: "Categorías"
    folder: "src/content/categorias"
    create: true
    slug: "{{fields.slug}}"  # ✅ CAMBIO CRÍTICO
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Slug debe ser minúsculas, números y guiones"] }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Color", name: "color", widget: "select", options: ["primary", "secondary", "success", "info"], default: "primary" }
      - { label: "Categoría padre", name: "parentCategory", widget: "relation", collection: "categories", search_fields: ["name"], value_field: "slug", display_fields: ["name"], required: false }
      - { label: "Orden", name: "order", widget: "number", min: 0, default: 0 }
      - { label: "Mostrar en navegación", name: "showInNavigation", widget: "boolean", default: true }
      - { label: "Mostrar en sidebar", name: "showInSidebar", widget: "boolean", default: true }
      - { label: "SEO Título", name: "seoTitle", widget: "string", required: false }
      - { label: "SEO Descripción", name: "seoDescription", widget: "string", required: false }

  # Colección de etiquetas (TERCERO)
  - name: "tags"
    label: "Etiquetas"
    folder: "src/content/etiquetas"
    create: true
    slug: "{{fields.slug}}"  # ✅ CAMBIO CRÍTICO
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Slug debe ser minúsculas, números y guiones"] }
      - { label: "Descripción", name: "description", widget: "text", required: false }
      - { label: "Categorías relacionadas", name: "categories", widget: "relation", collection: "categories", search_fields: ["name"], value_field: "slug", display_fields: ["name"], multiple: true, required: false }
      - { label: "Destacado", name: "featured", widget: "boolean", default: false }

  # Colección de artículos (AHORA CON RELACIONES CORRECTAS)
  collections:
  - name: "articulos"
    label: "Artículos"
    folder: "src/content/articulos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción/Bajada", name: "description", widget: "text"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Biografía del autor", name: "authorBio", widget: "text", required: false}
      - {label: "Imagen principal", name: "image", widget: "image"}
      - {label: "Categoría", name: "category", widget: "select", options: ["Razas", "Salud", "Comportamiento", "Alimentación", "Entrenamiento"]}
      - {label: "Etiquetas", name: "tags", widget: "list"}
      - {label: "Tiempo de lectura (minutos)", name: "readingTime", widget: "number"}
      - {label: "Artículo destacado", name: "featured", widget: "boolean", default: false}
      - {label: "Contenido", name: "body", widget: "markdown", 
         hint: "Usa ![descripción](URL) para insertar imágenes en el texto"}
      - {label: "Título SEO", name: "seoTitle", widget: "string", required: false}
      - {label: "Descripción SEO", name: "seoDescription", widget: "text", required: false}
  # Colección de razas
  - name: "breeds"
    label: "Razas"
    folder: "src/content/razas"
    create: true
    slug: "{{fields.slug}}"  # ✅ CAMBIO CRÍTICO
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Slug debe ser minúsculas, números y guiones"] }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imágenes", name: "images", widget: "list", field: { label: "Imagen", name: "image", widget: "image" } }
      - { label: "Tipo", name: "type", widget: "select", options: [{ label: "Perro", value: "dog" }, { label: "Gato", value: "cat" }] }
      - { label: "Tamaño", name: "size", widget: "select", options: [{ label: "Pequeño", value: "small" }, { label: "Mediano", value: "medium" }, { label: "Grande", value: "large" }] }
      - label: "Peso (kg)"
        name: "weight"
        widget: "object"
        fields:
          - { label: "Mínimo", name: "min", widget: "number", min: 0.1, step: 0.1 }
          - { label: "Máximo", name: "max", widget: "number", min: 0.1, step: 0.1 }
      - label: "Altura (cm)"
        name: "height"
        widget: "object"
        required: false
        fields:
          - { label: "Mínimo", name: "min", widget: "number", min: 1, step: 1 }
          - { label: "Máximo", name: "max", widget: "number", min: 1, step: 1 }
      - label: "Esperanza de vida (años)"
        name: "lifespan"
        widget: "object"
        fields:
          - { label: "Mínimo", name: "min", widget: "number", min: 1, step: 1 }
          - { label: "Máximo", name: "max", widget: "number", min: 1, step: 1 }
      - label: "Características"
        name: "traits"
        widget: "list"
        fields:
          - { label: "Nombre", name: "name", widget: "string" }
          - { label: "Valor (1-5)", name: "value", widget: "number", min: 1, max: 5, step: 1 }
          - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Buena convivencia con", name: "goodWith", widget: "select", options: ["children", "dogs", "cats", "seniors", "apartments"], multiple: true }
      - { label: "Nivel de energía (1-5)", name: "energyLevel", widget: "number", min: 1, max: 5, step: 1 }
      - { label: "Sociabilidad (1-5)", name: "friendliness", widget: "number", min: 1, max: 5, step: 1 }
      - { label: "Necesidad de cuidados (1-5)", name: "grooming", widget: "number", min: 1, max: 5, step: 1 }
      - { label: "Facilidad de entrenamiento (1-5)", name: "training", widget: "number", min: 1, max: 5, step: 1 }
      - { label: "Hipoalergénico", name: "hypoallergenic", widget: "boolean", default: false }
      - { label: "Historia", name: "history", widget: "markdown" }
      - { label: "Orígenes", name: "origins", widget: "markdown" }
      - { label: "Temperamento", name: "temperament", widget: "list" }
      - label: "Problemas de salud"
        name: "healthIssues"
        widget: "list"
        fields:
          - { label: "Nombre", name: "name", widget: "string" }
          - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Guía de cuidados", name: "careGuide", widget: "markdown" }
      - { label: "Razas similares", name: "similarBreeds", widget: "relation", collection: "breeds", search_fields: ["name"], value_field: "slug", display_fields: ["name"], multiple: true, required: false }
      - { label: "Destacado", name: "featured", widget: "boolean", default: false }
      - { label: "SEO Título", name: "seoTitle", widget: "string", required: false }
      - { label: "SEO Descripción", name: "seoDescription", widget: "string", required: false }

  # Colección de páginas
  - name: "pages"
    label: "Páginas"
    folder: "src/content/paginas"
    create: true
    slug: "{{fields.slug}}"  # ✅ CAMBIO CRÍTICO
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug (URL)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Slug debe ser minúsculas, números y guiones"] }
      - { label: "Contenido", name: "content", widget: "markdown" }
      - { label: "Fecha de creación", name: "createdAt", widget: "datetime" }
      - { label: "Fecha de actualización", name: "updatedAt", widget: "datetime" }
      - { label: "Mostrar en navegación", name: "showInNavigation", widget: "boolean", default: false }
      - { label: "Mostrar en footer", name: "showInFooter", widget: "boolean", default: true }
      - { label: "Orden en navegación", name: "navigationOrder", widget: "number", required: false }
      - { label: "Diseño", name: "layout", widget: "select", options: ["default", "full-width", "sidebar"], default: "default" }
      - { label: "Estado", name: "status", widget: "select", options: ["draft", "published", "archived"], default: "draft" }
      - { label: "SEO Título", name: "seoTitle", widget: "string", required: false }
      - { label: "SEO Descripción", name: "seoDescription", widget: "string", required: false }
      - { label: "Imagen SEO", name: "image", widget: "image", required: false }